version: '3.7'
networks:
  apinet:
    driver: bridge

services:
  url-shortener:
    image: url-shortener
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PSWD: rootpassword
    networks:
      - apinet
    volumes:
      - ./env.edn:/env.edn


  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    depends_on:
      - adminer
      - url-shortener
    ports:
      - 80:80
      - 443:443
    networks:
      - apinet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  mysql:
    image: mysql:latest
    # not recommended in production
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - apinet
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql_db_data_container:/var/lib/mysql

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql 
    networks:
      - apinet

volumes:
  mysql_db_data_container:
